# Form implementation generated from reading ui file 'progress_client.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(493, 261)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 110, 481, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Status_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.Status_lbl.setGeometry(QtCore.QRect(120, 20, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Status_lbl.setFont(font)
        self.Status_lbl.setObjectName("Status_lbl")
        self.Done_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Done_button.setGeometry(QtCore.QRect(172, 157, 91, 31))
        self.Done_button.setObjectName("Done_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Status_lbl.setText(_translate("MainWindow", "Файл загружается"))
        self.Done_button.setText(_translate("MainWindow", "Готово"))
