# Form implementation generated from reading ui file 'search_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 312)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_line.setGeometry(QtCore.QRect(20, 30, 251, 31))
        self.search_line.setObjectName("search_line")
        self.search_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(330, 30, 111, 31))
        self.search_btn.setObjectName("search_btn")
        self.download_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.download_btn.setGeometry(QtCore.QRect(330, 110, 81, 41))
        self.download_btn.setObjectName("download_btn")
        self.file_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.file_name.setGeometry(QtCore.QRect(20, 110, 291, 41))
        self.file_name.setText("")
        self.file_name.setObjectName("file_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_btn.setText(_translate("MainWindow", "Найти"))
        self.download_btn.setText(_translate("MainWindow", ""))
